# Data Cleaning for NOx emissions

### Import Packages

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import statsmodels
import plotly.io as pio
pio.renderers.default = "notebook"
import os
os.getcwd()

'/Users/maxlaurent/Documents/GitHub/Data_Science_Project'

### Load Data

In [6]:
df_NOx = pd.read_csv(
    "Emissions.csv",
    sep="\t",
    low_memory=False
)

df_NOx.head(10)

,countryCode,country,pollutantName,sectorCode,year,value,unit,notation,parentSectorCode,sectorName
0,AT,Austria,As,1B1b,2017,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
1,AT,Austria,As,1B1b,2018,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
2,AT,Austria,As,1B1b,2019,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
3,AT,Austria,As,1B1b,2020,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
4,AT,Austria,As,1B1b,2021,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
5,AT,Austria,As,1B1b,2022,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
6,AT,Austria,As,1B1b,2023,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
7,AT,Austria,As,1B1b,2024,NaN,t,NR,NATIONAL TOTAL,Fugitive emission from solid fuels: Solid fuel...
8,AT,Austria,As,1B1c,1990,NaN,t,NR,NATIONAL TOTAL,Other fugitive emissions from solid fuels
9,AT,Austria,As,1B1c,1991,NaN,t,NR,NATIONAL TOTAL,Other fugitive emissions from solid fuels

In [7]:
df_NOx.shape
df_NOx.columns.tolist()

['countryCode',
 'country',
 'pollutantName',
 'sectorCode',
 'year',
 'value',
 'unit',
 'notation',
 'parentSectorCode',
 'sectorName']

In [9]:
usecols = ["country","pollutantName","year","value","unit"]

df_NOx_useful = pd.read_csv(
    "Emissions.csv",
    sep="\t",
    usecols=usecols,
    low_memory=False
)

df_NOx_useful.head(10)

   country pollutantName  year  value unit
0  Austria            As  2017    NaN    t
1  Austria            As  2018    NaN    t
2  Austria            As  2019    NaN    t
3  Austria            As  2020    NaN    t
4  Austria            As  2021    NaN    t
5  Austria            As  2022    NaN    t
6  Austria            As  2023    NaN    t
7  Austria            As  2024    NaN    t
8  Austria            As  1990    NaN    t
9  Austria            As  1991    NaN    t

In [10]:
df_NOx_useful["pollutantName"].dropna().unique()

<StringArray>
[                        'As',                         'BC',
            'Benzo(a) Pyrene',      'Benzo(b) Fluoranthene',
      'benzo(k) Fluoranthene',                         'Cd',
                         'CO',   'Indeno (1,2,3-cd) Pyrene',
                        'NOx',                      'PM2.5',
                         'Zn',                         'Cr',
                         'Pb',                         'Se',
                        'NH3',                       'PCBs',
                         'Cu',                         'Ni',
                        'SOx', 'PCDD/PCDF (dioxins/furans)',
                      'NMVOC',                        'HCB',
                 'Total PAHs',                       'PM10',
                        'TSP',                         'Hg',
                    'Biomass',              'Gaseous Fuels',
               'Liquid Fuels',                'Other Fuels',
                'Solid Fuels']
Length: 31, dtype: str

In [15]:
df_NOx_onlyNOx = df_NOx_useful[
    df_NOx_useful["pollutantName"]
    .str.upper()
    .eq("NOX")
].copy()

df_NOx_onlyNOx.head()

       country pollutantName  year  value unit
25945  Austria           NOx  2023    NaN   kt
25946  Austria           NOx  2024    NaN   kt
25947  Austria           NOx  1987    NaN   kt
25948  Austria           NOx  1988    NaN   kt
25949  Austria           NOx  1989    NaN   kt

In [18]:
df_NOx_onlyNOx = df_NOx_onlyNOx.dropna(subset=["value"]).copy()

df_NOx_onlyNOx["country"].unique()

<StringArray>
[      'Austria',       'Belgium',      'Bulgaria',        'Cyprus',
       'Czechia',       'Germany',       'Denmark',       'Estonia',
         'Spain',       'Finland',        'France',        'Greece',
       'Croatia',       'Hungary',       'Ireland',         'Italy',
     'Lithuania',    'Luxembourg',        'Latvia',         'Malta',
   'Netherlands',        'Poland',      'Portugal',       'Romania',
        'Sweden',      'Slovenia',      'Slovakia',   'Switzerland',
       'Iceland', 'Liechtenstein',        'Norway',       'Türkiye',
         'EEA32',          'EU27']
Length: 34, dtype: str

In [22]:
df_NOx_NS = df_NOx_onlyNOx[
    df_NOx_onlyNOx["country"].isin(["Norway", "Sweden"])
].copy()

df_NOx_NS.head(40)

        country pollutantName  year      value unit
3055171  Sweden           NOx  1987  14.338300   kt
3055440  Sweden           NOx  1988  14.338300   kt
3055441  Sweden           NOx  1989  14.338300   kt
3055442  Sweden           NOx  1990  14.338300   kt
3055443  Sweden           NOx  1991  16.626700   kt
3055444  Sweden           NOx  1992  15.808800   kt
3055445  Sweden           NOx  1993  14.851100   kt
3055446  Sweden           NOx  1994  15.548000   kt
3055447  Sweden           NOx  1995  12.128100   kt
3055448  Sweden           NOx  1996  14.978100   kt
3055449  Sweden           NOx  1997  10.750200   kt
3055450  Sweden           NOx  1998  11.688600   kt
3055451  Sweden           NOx  1999  10.587300   kt
3055452  Sweden           NOx  2000   8.989480   kt
3055453  Sweden           NOx  2001   9.394200   kt
3055454  Sweden           NOx  2002  11.431700   kt
3055455  Sweden           NOx  2003  12.606200   kt
3055456  Sweden           NOx  2004  11.567800   kt
3055457  Sweden           NOx  2005  11.991700   kt
3055458  Sweden           NOx  2006  12.279900   kt
3055459  Sweden           NOx  2007  10.818100   kt
3055460  Sweden           NOx  2008  11.433600   kt
3055461  Sweden           NOx  2009  12.605500   kt
3055462  Sweden           NOx  2010  14.999300   kt
3055463  Sweden           NOx  2011  12.357500   kt
3055464  Sweden           NOx  2012  12.292000   kt
3055465  Sweden           NOx  2013  11.618700   kt
3055466  Sweden           NOx  2014  10.890900   kt
3055467  Sweden           NOx  2015  10.979700   kt
3055468  Sweden           NOx  2016  11.944900   kt
3055469  Sweden           NOx  2017  11.922500   kt
3055470  Sweden           NOx  2018  12.067300   kt
3055471  Sweden           NOx  2019  11.871700   kt
3055472  Sweden           NOx  2020  10.635800   kt
3055473  Sweden           NOx  2021  13.158400   kt
3055474  Sweden           NOx  2022  12.694100   kt
3055475  Sweden           NOx  2023  12.180800   kt
3055476  Sweden           NOx  2024  11.563200   kt
3055586  Sweden           NOx  1987   3.069809   kt
3055587  Sweden           NOx  1988   2.926952   kt